/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gzhqqdjmmiobbniiqvxl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aHFxZGptbWlvYmJuaWlxdnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyODQyMzgsImV4cCI6MjEwMjg2MDIzOH0._2aS9kJP26ppCfjIruU-WD2iy1xOX7dGFh-C0TvzKGg"